# A Good First Program
print("Hello World")
print("Hello world again")
#print("I like typing this")
print("This is fun")
print('Yay! printing')
#print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("Manchester United is Love <3")
print("Uefa europa league Starts tonight" )